name: build and release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the version tag for the release:'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
      # ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    strategy:
      fail-fast: false
      matrix:
        os: [linux, darwin, windows, freebsd]
        arch: [amd64, arm64, 386, loong64, mips, mips64, mips64le, mipsle, riscv64]
        exclude:
          - os: windows
            arch: loong64
          - os: windows
            arch: mips
          - os: windows
            arch: mips64
          - os: windows
            arch: mips64le
          - os: windows
            arch: mipsle
          - os: windows
            arch: riscv64
          - os: freebsd
            arch: loong64
          - os: freebsd
            arch: mips
          - os: freebsd
            arch: mips64
          - os: freebsd
            arch: mips64le
          - os: freebsd
            arch: mipsle
          - os: freebsd
            arch: riscv64
          - os: darwin
            arch: 386
          - os: darwin
            arch: loong64
          - os: darwin
            arch: mips
          - os: darwin
            arch: mips64
          - os: darwin
            arch: mips64le
          - os: darwin
            arch: mipsle
          - os: darwin
            arch: riscv64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'

      - name: Determine version
        id: determine_version
        run: |
          if [[ -z "${{ github.event.inputs.version }}" ]]; then
            VERSION=$(git describe --tags --always)
          else
            VERSION="${{ github.event.inputs.version }}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Gather build information
        id: gather_build_info
        run: |
          echo "buildtime=$(date -u '+%Y-%m-%d_%I:%M:%S%p(UTC%:z)')" >> $GITHUB_OUTPUT
          echo "commit=$(git rev-parse --short HEAD || echo 'Unknown')" >> $GITHUB_OUTPUT

      - name: Generate certificates and build application
        env:
          GOARCH: ${{ matrix.arch }}
          GOOS: ${{ matrix.os }}
          MS_BUILDTOKEN: ${{ secrets.MS_BUILDTOKEN }}
          VERSION: ${{ steps.determine_version.outputs.version }}
          BUILDTIME: ${{ steps.gather_build_info.outputs.buildtime }}
          COMMIT: ${{ steps.gather_build_info.outputs.commit }}
        run: |
          echo $MS_BUILDTOKEN >> ./utils/embeded/BUILDTOKEN.key
          mkdir -p ./preconfigs/embeded/miaokoCA
          openssl req -x509 -newkey ec:<(openssl ecparam -name secp256r1) -nodes -keyout ./preconfigs/embeded/miaokoCA/miaoko.key -out ./preconfigs/embeded/miaokoCA/miaoko.crt -subj "/CN=fulltclash.com"
          CGO_ENABLED=0 GOOS=$GOOS GOARCH=$GOARCH go build -trimpath -ldflags "-X 'main.VERSION=$VERSION' -X 'main.COMPILATIONTIME=$BUILDTIME' -X 'main.COMMIT=$COMMIT' -w -s -buildid=" -o miaospeed_${GOOS}_${GOARCH} .

      - name: Optimize with UPX
        run: |
          upx --best --lzma miaospeed_${{ matrix.os }}_${{ matrix.arch }}

      - name: Archive the build artifacts
        run: |
          if [ "${{ matrix.os }}" == "windows" ]; then
            zip miaospeed_${{ matrix.os }}_${{ matrix.arch }}_${{ steps.determine_version.outputs.version }}.zip miaospeed_${{ matrix.os }}_${{ matrix.arch }}
          else
            tar -czvf miaospeed_${{ matrix.os }}_${{ matrix.arch }}_${{ steps.determine_version.outputs.version }}.tar.gz miaospeed_${{ matrix.os }}_${{ matrix.arch }}
          fi

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: "v${{ github.event.inputs.version }}"
          body: "More new features are now supported."
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            miaospeed_${{ matrix.os }}_${{ matrix.arch }}_${{ steps.determine_version.outputs.version }}.tar.gz
            miaospeed_${{ matrix.os }}_${{ matrix.arch }}_${{ steps.determine_version.outputs.version }}.zip

  update_tag:
    name: Update tag
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Env
        run: |
          echo "BUILDTIME=$(TZ=Asia/Shanghai date)" >> $GITHUB_ENV
        shell: bash

      - name: Update Tag
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          cat > release.txt << 'EOF'
          ## 我应该下载哪个版本？
          一般下载amd64版本即可，其他平台根据实际情况下载对应的版本。
          Created at ${{ env.BUILDTIME }}.
          EOF

      - name: Upload Release Notes
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: "v${{ github.event.inputs.version }}"
          body_path: release.txt
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
