name: build and release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the version tag for the release:'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
      # ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'

      - name: Determine version
        id: determine_version
        run: |
          if [[ -z "${{ github.event.inputs.version }}" ]]; then
            VERSION=$(git describe --tags --always)
          else
            VERSION="${{ github.event.inputs.version }}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Gather build information
        id: gather_build_info
        run: |
          echo "buildtime=$(date -u '+%Y-%m-%d_%I:%M:%S%p(UTC%:z)')" >> $GITHUB_OUTPUT
          echo "commit=$(git rev-parse --short HEAD || echo 'Unknown')" >> $GITHUB_OUTPUT

      - name: Generate certificates and build
        env:
          GOARCH: ${{ matrix.arch }}
          MS_BUILDTOKEN: ${{ secrets.MS_BUILDTOKEN }}
          VERSION: ${{ steps.determine_version.outputs.version }}
          BUILDTIME: ${{ steps.gather_build_info.outputs.buildtime }}
          COMMIT: ${{ steps.gather_build_info.outputs.commit }}
        run: |
          echo $MS_BUILDTOKEN >> ./utils/embeded/BUILDTOKEN.key
          mkdir -p ./preconfigs/embeded/miaokoCA
          openssl req -x509 -newkey ec:<(openssl ecparam -name secp256r1) -nodes -keyout ./preconfigs/embeded/miaokoCA/miaoko.key -out ./preconfigs/embeded/miaokoCA/miaoko.crt -subj "/CN=fulltclash.com"
          CGO_ENABLED=0 GOOS=linux GOARCH=$GOARCH go build -trimpath -ldflags "-X 'main.VERSION=$VERSION' -X 'main.COMPILATIONTIME=$BUILDTIME' -X 'main.COMMIT=$COMMIT' -w -s -buildid=" -o miaospeed_${GOARCH} .

      - name: Archive the build
        run: |
          tar -czvf miaospeed_${{ matrix.arch }}.tar.gz miaospeed_${{ matrix.arch }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: miaospeed_${{ matrix.arch }}.tar.gz
          path: miaospeed_${{ matrix.arch }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          echo "BUILDTIME=$(TZ=Asia/Shanghai date)" >> $GITHUB_ENV
        shell: bash

      - name: Create Release Notes
        run: |
          cat > release.txt << 'EOF'
          ## 我应该下载哪个版本？

          Created at ${{ env.BUILDTIME }}.
          EOF

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: "miaospeed for fulltclash ${{ github.event.inputs.version }}"
          body_path: release.txt
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true

      - name: Upload Assets to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/*
